import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'surface-tint': '#4d44e3',
        'inverse-primary': '#c3c0ff',
        'tertiary-fixed': '#6ffbbe',
        'surface-dim': '#d8dadc',
        'on-background': '#191c1e',
        'primary-fixed': '#e2dfff',
        'tertiary-container': '#006e4b',
        'secondary-container': '#8a4cfc',
        'on-primary-container': '#dad7ff',
        'inverse-surface': '#2d3133',
        'surface-container-lowest': '#ffffff',
        'error': '#ba1a1a',
        'outline-variant': '#c7c4d8',
        'surface-bright': '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'secondary': '#712ae2',
        'surface-container': '#eceef0',
        'tertiary-fixed-dim': '#4edea3',
        'secondary-fixed-dim': '#d2bbff',
        'error-container': '#ffdad6',
        'surface-container-low': '#f2f4f6',
        'primary-container': '#4f46e5',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#0f0069',
        'surface': '#f7f9fb',
        'on-tertiary-container': '#67f4b7',
        'on-secondary-container': '#fffbff',
        'outline': '#777587',
        'tertiary': '#005338',
        'on-tertiary-fixed-variant': '#005236',
        'background': '#f7f9fb',
        'on-secondary-fixed-variant': '#5a00c6',
        'on-tertiary-fixed': '#002113',
        'surface-container-highest': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'primary': '#3525cd',
        'on-surface-variant': '#464555',
        'on-secondary-fixed': '#25005a',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#3323cc',
        'secondary-fixed': '#eaddff',
        'on-surface': '#191c1e',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'card': '0 12px 32px rgba(53, 37, 205, 0.06)',
        'card-sm': '0 4px 16px rgba(0, 0, 0, 0.02)',
        'cta': '0 12px 32px rgba(53, 37, 205, 0.15)',
        'nav': '0 -12px 32px rgba(53, 37, 205, 0.06)',
        'modal': '0 12px 32px rgba(53, 37, 205, 0.06)',
      },
    },
  },
  plugins: [],
} satisfies Config;
